name: Docker Hub 镜像转存至阿里云镜像仓库

on:
  push:
    branches:
      - main  # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_SRC: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}
      IMAGES: dpage/pgadmin4:8.8,node:20,nginx:1.27

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKERHUB_USERNAME }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Log in to Docker Hub
        # 登录阿里云镜像仓库
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_REGISTRY }} --password-stdin

      - name: Pull Docker image from Docker Hub and Push Docker image to Aliyun
        run: |
        
          IFS=',' read -ra images <<< ${{ env.IMAGES }}

          for image_name in ${images[@]}; do
            # pull the romote image from the registry
            docker pull $image_name

            # Tag the local image with the remote
            image_name_new=$(echo "$image_name" | awk -F'/' '{ if (NF > 1) print $2; else print $0 }') 
            docker tag $image_name ${{ env.IMAGE_SRC }}/$image_name_new

            # push the remote image
            docker push ${{ env.IMAGE_SRC }}/$image_name_new

            # echo
            echo  ******** 镜像: $image_name 推送成功********
          done

