name: Docker Hub to Aliyun Transfer

on:
  push:
    branches:
      - main  # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_IMAGE: dpage/pgadmin4:8.8  # Docker Hub 镜像
      ALIYUN_IMAGE: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/pgadmin4:8.8  # 阿里云镜像

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Log in to Docker Hub
    #   run: echo "${{ secrets.DOCKERHUB_USERNAME }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Pull Docker image from Docker Hub
      run: docker pull ${{ env.DOCKERHUB_IMAGE }}

    - name: Push Docker image to Aliyun
      run: |
        docker version
        # 登录阿里云镜像仓库
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password-stdin=${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
        # 镜像打标签
        docker tag ${{ env.DOCKERHUB_IMAGE }} ${{ env.ALIYUN_IMAGE }}
        # 推送镜像到镜像仓库
        docker push ${{ env.ALIYUN_IMAGE }}
